In [1]:
import torch
A = torch.tensor([[1, 2], [3, 4]])
A.sum(axis=0), A.sum(axis=1)

(tensor([4, 6]), tensor([3, 7]))

In [3]:
A = torch.ones(2,5,4)
A.sum(axis=1).shape, A.sum(axis=2).shape
A.sum(axis=1), A.sum(axis=2)

(tensor([[5., 5., 5., 5.],
         [5., 5., 5., 5.]]),
 tensor([[4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.]]))